all: bins p1 p2 p3 p4 p5

bins:
	mkdir -p bins

clean:
	rm -rf bins

p1: p1.c
	gcc -o bins/p1 p1.c -Wall

p2: p2.c
	gcc -o bins/p2 p2.c -Wall

p3: p3.c
	gcc -o bins/p3 p3.c -Wall

p4: p4.c
	gcc -o bins/p4 p4.c -Wall

p5: p5.c
	gcc -o bins/p5 p5.c -Wall
