all: bins p1 p2 p3 p4 p5 p6 p7 p8 p9 p10 p11 p12

bins:
	mkdir -p bins

clean:
	rm -rf bins

p1: p1.c
	gcc -o bins/p1 p1.c -Wall

p2: p2.c
	gcc -o bins/p2 p2.c -Wall

p3: p3.c
	gcc -o bins/p3 p3.c -Wall

p4: p4.c
	gcc -o bins/p4 p4.c -Wall

p5: p5.c
	gcc -o bins/p5 p5.c -Wall

p6: p6.c
	gcc -o bins/p6 p6.c -Wall

p7: p7.c
	gcc -o bins/p7 p7.c -Wall

p8: p8.c
	gcc -o bins/p8 p8.c -Wall

p9: p9.c
	gcc -o bins/p9 p9.c -Wall

p10: p10.c
	gcc -o bins/p10 p10.c -Wall

p11: p11.c
	gcc -o bins/p11 p11.c -Wall

p12: p12.c
	gcc -o bins/p12 p12.c -Wall